# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - HelloVigna83-

jobs:
- job: MyServerJob
  pool:
    name: server

  steps:
  - task: InvokeRESTAPI@1
    displayName: 'Invoke REST API: GET'
    inputs:
      serviceConnection: 'github.com_BhavaniN5'
      method: GET
      successCriteria: 'eq(root[''count''], ''1425'')'
